pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        stage('Create Schema') {
            steps {
                sh "python3 create.py"
            }
        }
        //stage('Run') {
        //    steps {
        //        //
        //    }
        //}
    }
}